"""
constants.py - Constantes do módulo de Acordos.

Constantes de status, tipos e opções para acordos e cláusulas.
"""

from .models import (
    STATUS_OPTIONS,
    STATUS_RASCUNHO,
    STATUS_ATIVO,
    STATUS_ARQUIVADO,
    STATUS_CANCELADO,
    CLAUSULA_STATUS_OPTIONS,
    CLAUSULA_STATUS_CUMPRIDA,
    CLAUSULA_STATUS_PENDENTE,
    CLAUSULA_STATUS_ATRASADA,
    CLAUSULA_TIPO_OPTIONS,
    CLAUSULA_TIPO_GERAL,
    CLAUSULA_TIPO_ESPECIFICA,
)

__all__ = [
    'STATUS_OPTIONS',
    'STATUS_RASCUNHO',
    'STATUS_ATIVO',
    'STATUS_ARQUIVADO',
    'STATUS_CANCELADO',
    'CLAUSULA_STATUS_OPTIONS',
    'CLAUSULA_STATUS_CUMPRIDA',
    'CLAUSULA_STATUS_PENDENTE',
    'CLAUSULA_STATUS_ATRASADA',
    'CLAUSULA_TIPO_OPTIONS',
    'CLAUSULA_TIPO_GERAL',
    'CLAUSULA_TIPO_ESPECIFICA',
]

